# Lab | Data Aggregation and Filtering

En este desafío, continuaremos trabajando con datos de clientes de una compañía de seguros. Usaremos el conjunto de datos llamado marketing_customer_analysis.csv, que se puede encontrar en el siguiente enlace:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

Este conjunto de datos contiene información como datos demográficos del cliente, detalles de la política, información del vehículo y la respuesta del cliente a la última campaña de marketing. Nuestro objetivo es explorar y analizar estos datos realizando primero una limpieza, formateo y estructuración de datos.

1. Create a new DataFrame that only includes clients that:
   - have a **low total_claim_amount** (for example, less than $1000),
   - have a "Yes" response to the latest marketing campaign.

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

3. Analyze the total number of customers who have policies in each state and then filter the results to include only states where there are more than 500 customers.

4. Find the maximum, minimum and average value of the client's life by educational level and gender. Write your conclusions.

## Bonus

5. El equipo de ventas debe revisar la cantidad de pólizas vendidas por gobierno y mes. Proporcione los datos en una tabla donde los meses estén ordenados en columnas y los países en filas.

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [1]:
import pandas as pd

url = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv'
df = pd.read_csv(url)
df.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN


In [2]:
df_filtrado = df[(df['Total Claim Amount'] < 1000) & (df['Response'] == 'Yes')].copy()
df_filtrado.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN


In [3]:
df.columns

Index(['Unnamed: 0', 'Customer', 'State', 'Customer Lifetime Value',
       'Response', 'Coverage', 'Education', 'Effective To Date',
       'EmploymentStatus', 'Gender', 'Income', 'Location Code',
       'Marital Status', 'Monthly Premium Auto', 'Months Since Last Claim',
       'Months Since Policy Inception', 'Number of Open Complaints',
       'Number of Policies', 'Policy Type', 'Policy', 'Renew Offer Type',
       'Sales Channel', 'Total Claim Amount', 'Vehicle Class', 'Vehicle Size',
       'Vehicle Type'],
      dtype='str')

In [4]:
df_yes = df[df['Response'] == 'Yes']
df_yes.describe()

,Unnamed: 0,Customer Lifetime Value,Income,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Total Claim Amount
count,1466.000000,1466.000000,1466.000000,1466.000000,1388.000000,1466.000000,1388.000000,1466.000000,1466.000000
mean,5369.644611,7882.547917,38395.844475,94.412688,14.749280,47.746248,0.371758,2.865621,447.061570
std,3152.913023,6314.253798,27963.788042,36.191445,9.732572,27.079274,0.918516,2.430260,239.643280
min,3.000000,2004.350666,0.000000,61.000000,0.000000,0.000000,0.000000,1.000000,7.345946
25%,2582.500000,3954.344534,18495.000000,68.000000,6.000000,24.000000,0.000000,1.000000,316.800000
50%,5417.000000,5597.124960,33806.000000,86.000000,14.000000,50.000000,0.000000,2.000000,412.800000
75%,7997.250000,9075.768214,60475.000000,109.000000,22.000000,69.000000,0.000000,3.000000,547.200000
max,10897.000000,41787.903430,99845.000000,283.000000,35.000000,99.000000,5.000000,9.000000,1358.400000


In [5]:
df_yes.groupby(['Policy Type', 'Gender'])[['Monthly Premium Auto', 'Customer Lifetime Value', 'Total Claim Amount']].mean().round(0)

Monthly Premium Auto  Customer Lifetime Value  \
Policy Type    Gender                                                  
Corporate Auto F                       94.0                   7713.0   
               M                       92.0                   7944.0   
Personal Auto  F                       99.0                   8340.0   
               M                       91.0                   7448.0   
Special Auto   F                       92.0                   7692.0   
               M                       86.0                   8247.0   

                       Total Claim Amount  
Policy Type    Gender                      
Corporate Auto F                    434.0  
               M                    409.0  
Personal Auto  F                    453.0  
               M                    457.0  
Special Auto   F                    453.0  
               M                    430.0

1.Segmento mas rentable :
- Corresponde al de Mujeres 'F' en 'Personal Auto', ya que es la que paga el mayor 'Monthly Premium Auto'(99.0)

2.segmento con menor riesgo:
- Corresponde al de Hombres 'M' en Corporate Auto, tiene el menor TCA(409.0)


In [6]:
grouped = df.groupby('State')
grouped
grouped.size()

State
Arizona       1937
California    3552
Nevada         993
Oregon        2909
Washington     888
dtype: int64

In [7]:
states_over_500 = df.groupby('State').size()
states_over_500 = states_over_500[states_over_500 > 500]
states_over_500

State
Arizona       1937
California    3552
Nevada         993
Oregon        2909
Washington     888
dtype: int64

In [11]:
df_analisis = df.groupby(['Education', 'Gender'])['Customer Lifetime Value'].agg(['max', 'min', 'mean'])
df_analisis

max          min         mean
Education            Gender                                       
Bachelor             F       73225.95652  1904.000852  7874.269478
                     M       67907.27050  1898.007675  7703.601675
College              F       61850.18803  1898.683686  7748.823325
                     M       61134.68307  1918.119700  8052.459288
Doctor               F       44856.11397  2395.570000  7328.508916
                     M       32677.34284  2267.604038  7415.333638
High School or Below F       55277.44589  2144.921535  8675.220201
                     M       83325.38119  1940.981221  8149.687783
Master               F       51016.06704  2417.777032  8157.053154
                     M       50568.25912  2272.307310  8168.832659

CONCLUSIONES:

1. los valores mas altos estan en 'High School or Below', es probable que sean los apoderados o padres los que esten solventando esa cantidad o son adolescentes de familias muy adineradas.
2. los valores con un menor valor se encuentran en el sector de 'Doctor', es probable debido a que, son personas que se dedican solo  al doctorado